In [2]:
import pandas as pd

file_path = '2015-01-01-15.json.gz'
data = pd.read_json(file_path, lines=True)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11351 entries, 0 to 11350
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          11351 non-null  int64
 1   type        11351 non-null  object
 2   actor       11351 non-null  object
 3   repo        11351 non-null  object
 4   payload     11351 non-null  object
 5   public      11351 non-null  bool
 6   created_at  11351 non-null  datetime64[ns, UTC]
 7   org         3245 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), int64(1), object(5)
memory usage: 632.0+ KB

In [4]:
data.head(10)

,id,type,actor,repo,payload,public,created_at,org
0,2489651045,CreateEvent,"{'id': 665991, 'login': 'petroav', 'gravatar_i...","{'id': 28688495, 'name': 'petroav/6.828', 'url...","{'ref': 'master', 'ref_type': 'branch', 'maste...",True,2015-01-01 15:00:00+00:00,NaN
1,2489651051,PushEvent,"{'id': 3854017, 'login': 'rspt', 'gravatar_id'...","{'id': 28671719, 'name': 'rspt/rspt-theme', 'u...","{'push_id': 536863970, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:01+00:00,NaN
2,2489651053,PushEvent,"{'id': 6339799, 'login': 'izuzero', 'gravatar_...","{'id': 28270952, 'name': 'izuzero/xe-module-aj...","{'push_id': 536863972, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:01+00:00,NaN
3,2489651057,WatchEvent,"{'id': 6894991, 'login': 'SametSisartenep', 'g...","{'id': 2871998, 'name': 'visionmedia/debug', '...",{'action': 'started'},True,2015-01-01 15:00:03+00:00,"{'id': 9285252, 'login': 'visionmedia', 'grava..."
4,2489651062,PushEvent,"{'id': 485033, 'login': 'winterbe', 'gravatar_...","{'id': 28593843, 'name': 'winterbe/streamjs', ...","{'push_id': 536863975, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:03+00:00,NaN
5,2489651063,PushEvent,"{'id': 4319954, 'login': 'hermanwahyudi', 'gra...","{'id': 27826205, 'name': 'hermanwahyudi/seleni...","{'push_id': 536863976, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:03+00:00,NaN
6,2489651064,PushEvent,"{'id': 2881602, 'login': 'jdilt', 'gravatar_id...","{'id': 28682546, 'name': 'jdilt/jdilt.github.i...","{'push_id': 536863977, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:03+00:00,NaN
7,2489651066,PushEvent,"{'id': 3495129, 'login': 'sundaymtn', 'gravata...","{'id': 24147122, 'name': 'sundaymtn/waterline'...","{'push_id': 536863979, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:04+00:00,NaN
8,2489651067,PushEvent,"{'id': 10363514, 'login': 'zhouzhi2015', 'grav...","{'id': 28686619, 'name': 'zhouzhi2015/temp', '...","{'push_id': 536863980, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:04+00:00,NaN
9,2489651071,ReleaseEvent,"{'id': 7659931, 'login': 'petrkutalek', 'grava...","{'id': 20029610, 'name': 'petrkutalek/png2pos'...","{'action': 'published', 'release': {'url': 'ht...",True,2015-01-01 15:00:05+00:00,NaN

In [10]:
print(data['actor'][0])
print()
print(data['repo'][0])
print()
print(data['payload'][0])

{'id': 665991, 'login': 'petroav', 'gravatar_id': '', 'url': 'https://api.github.com/users/petroav', 'avatar_url': 'https://avatars.githubusercontent.com/u/665991?'}

{'id': 28688495, 'name': 'petroav/6.828', 'url': 'https://api.github.com/repos/petroav/6.828'}

{'ref': 'master', 'ref_type': 'branch', 'master_branch': 'master', 'description': "Solution to homework and assignments from MIT's 6.828 (Operating Systems Engineering). Done in my spare time.", 'pusher_type': 'user'}

In [15]:
# type column만 따로 살펴보자
types = [i for i in data['type']]
type_set = set()
for i in types:
    type_set.add(i)
type_set

{'CommitCommentEvent',
 'CreateEvent',
 'DeleteEvent',
 'ForkEvent',
 'GollumEvent',
 'IssueCommentEvent',
 'IssuesEvent',
 'MemberEvent',
 'PublicEvent',
 'PullRequestEvent',
 'PullRequestReviewCommentEvent',
 'PushEvent',
 'ReleaseEvent',
 'WatchEvent'}

In [17]:
from collections import Counter
Counter(types)

Counter({'CreateEvent': 1471,
         'PushEvent': 5815,
         'WatchEvent': 1230,
         'ReleaseEvent': 60,
         'PullRequestEvent': 474,
         'IssuesEvent': 545,
         'ForkEvent': 355,
         'GollumEvent': 61,
         'IssueCommentEvent': 844,
         'DeleteEvent': 260,
         'PullRequestReviewCommentEvent': 136,
         'CommitCommentEvent': 73,
         'MemberEvent': 25,
         'PublicEvent': 2})

In [19]:
# PushEvent와 CreateEvent, WatchEvent가 월등히 높다.

In [24]:
# 어떤 정보일 때 상대방 깃을 Watch나 Fork하는 비율이 높을까? (Watch나 Fork가 높은 repo가 star가 많지 않을까..)
from IPython.display import display
data_watch = data[data['type'] == 'WatchEvent']
data_fork = data[data['type'] == 'ForkEvent']
display(data_watch)
display(data_fork)

,id,type,actor,repo,payload,public,created_at,org
3,2489651057,WatchEvent,"{'id': 6894991, 'login': 'SametSisartenep', 'g...","{'id': 2871998, 'name': 'visionmedia/debug', '...",{'action': 'started'},True,2015-01-01 15:00:03+00:00,"{'id': 9285252, 'login': 'visionmedia', 'grava..."
11,2489651078,WatchEvent,"{'id': 285289, 'login': 'comcxx11', 'gravatar_...","{'id': 5569958, 'name': 'phpsysinfo/phpsysinfo...",{'action': 'started'},True,2015-01-01 15:00:05+00:00,"{'id': 6797923, 'login': 'phpsysinfo', 'gravat..."
12,2489651080,WatchEvent,"{'id': 1757814, 'login': 'Soufien', 'gravatar_...","{'id': 25873041, 'name': 'wasabeef/awesome-and...",{'action': 'started'},True,2015-01-01 15:00:05+00:00,NaN
17,2489651093,WatchEvent,"{'id': 546301, 'login': 'unicomp21', 'gravatar...","{'id': 10635999, 'name': 'dartist/raytracer', ...",{'action': 'started'},True,2015-01-01 15:00:06+00:00,"{'id': 3138716, 'login': 'dartist', 'gravatar_..."
27,2489651114,WatchEvent,"{'id': 1209286, 'login': 'lucker6666', 'gravat...","{'id': 25062303, 'name': 'googlesamples/androi...",{'action': 'started'},True,2015-01-01 15:00:08+00:00,"{'id': 7378196, 'login': 'googlesamples', 'gra..."
...,...,...,...,...,...,...,...,...
11298,2489678729,WatchEvent,"{'id': 109821, 'login': 'TheX', 'gravatar_id':...","{'id': 8538132, 'name': 'designmodo/Flat-UI', ...",{'action': 'started'},True,2015-01-01 15:59:42+00:00,"{'id': 3756424, 'login': 'designmodo', 'gravat..."
11300,2489678731,WatchEvent,"{'id': 144652, 'login': 'zhex', 'gravatar_id':...","{'id': 13124802, 'name': 'influxdb/influxdb', ...",{'action': 'started'},True,2015-01-01 15:59:42+00:00,"{'id': 5713248, 'login': 'influxdb', 'gravatar..."
11307,2489678741,WatchEvent,"{'id': 8668716, 'login': 'sagniksaha', 'gravat...","{'id': 11180687, 'name': 'spf13/hugo', 'url': ...",{'action': 'started'},True,2015-01-01 15:59:44+00:00,NaN
11322,2489678785,WatchEvent,"{'id': 8945275, 'login': 'julian-wang', 'grava...","{'id': 28225310, 'name': 'StevenSLXie/Tutorial...",{'action': 'started'},True,2015-01-01 15:59:50+00:00,NaN
11345,2489678837,WatchEvent,"{'id': 8241538, 'login': 'seccode', 'gravatar_...","{'id': 2126244, 'name': 'twbs/bootstrap', 'url...",{'action': 'started'},True,2015-01-01 15:59:59+00:00,"{'id': 2918581, 'login': 'twbs', 'gravatar_id'..."

,id,type,actor,repo,payload,public,created_at,org
36,2489651128,ForkEvent,"{'id': 1757814, 'login': 'Soufien', 'gravatar_...","{'id': 25873041, 'name': 'wasabeef/awesome-and...","{'forkee': {'id': 28688599, 'name': 'awesome-a...",True,2015-01-01 15:00:10+00:00,NaN
92,2489651282,ForkEvent,"{'id': 1757814, 'login': 'Soufien', 'gravatar_...","{'id': 26689598, 'name': 'prakhar1989/awesome-...","{'forkee': {'id': 28688604, 'name': 'awesome-c...",True,2015-01-01 15:00:23+00:00,NaN
228,2489651661,ForkEvent,"{'id': 1772762, 'login': 'mobilipia', 'gravata...","{'id': 481412, 'name': 'TooTallNate/Java-WebSo...","{'forkee': {'id': 28688618, 'name': 'Java-WebS...",True,2015-01-01 15:01:15+00:00,NaN
241,2489651703,ForkEvent,"{'id': 3161587, 'login': 'mmdanggg2', 'gravata...","{'id': 8632474, 'name': 'jadar/DeveloperCapes'...","{'forkee': {'id': 28688620, 'name': 'Developer...",True,2015-01-01 15:01:20+00:00,NaN
265,2489651771,ForkEvent,"{'id': 1218095, 'login': 'superzhang', 'gravat...","{'id': 3261830, 'name': 'tommy351/Octopress-Th...","{'forkee': {'id': 28688624, 'name': 'Octopress...",True,2015-01-01 15:01:29+00:00,NaN
...,...,...,...,...,...,...,...,...
11245,2489678619,ForkEvent,"{'id': 177122, 'login': 'Songmu', 'gravatar_id...","{'id': 5664236, 'name': 'book/App-Wallflower',...","{'forkee': {'id': 28689731, 'name': 'App-Wallf...",True,2015-01-01 15:59:26+00:00,NaN
11248,2489678622,ForkEvent,"{'id': 10239381, 'login': 'bigbigwork', 'grava...","{'id': 7117833, 'name': 'endel/joy.js', 'url':...","{'forkee': {'id': 28689732, 'name': 'joy.js', ...",True,2015-01-01 15:59:27+00:00,NaN
11271,2489678677,ForkEvent,"{'id': 3809454, 'login': 'dani0l', 'gravatar_i...","{'id': 21183062, 'name': 'drewsdunne/BatteryPe...","{'forkee': {'id': 28689737, 'name': 'BatteryPe...",True,2015-01-01 15:59:36+00:00,NaN
11301,2489678732,ForkEvent,"{'id': 10365077, 'login': 'jallen0188', 'grava...","{'id': 11927247, 'name': 'punkave/jquery-json-...","{'forkee': {'id': 28689738, 'name': 'jquery-js...",True,2015-01-01 15:59:42+00:00,"{'id': 1099262, 'login': 'punkave', 'gravatar_..."
11304,2489678735,ForkEvent,"{'id': 109821, 'login': 'TheX', 'gravatar_id':...","{'id': 8538132, 'name': 'designmodo/Flat-UI', ...","{'forkee': {'id': 28689739, 'name': 'Flat-UI',...",True,2015-01-01 15:59:43+00:00,"{'id': 3756424, 'login': 'designmodo', 'gravat..."

In [25]:
# 어떤 정보인지 알기 위해 payload만 한번 보자
data_watch['payload']

3        {'action': 'started'}
11       {'action': 'started'}
12       {'action': 'started'}
17       {'action': 'started'}
27       {'action': 'started'}
                 ...
11298    {'action': 'started'}
11300    {'action': 'started'}
11307    {'action': 'started'}
11322    {'action': 'started'}
11345    {'action': 'started'}
Name: payload, Length: 1230, dtype: object

In [35]:
data_fork['payload']

36       {'forkee': {'id': 28688599, 'name': 'awesome-a...
92       {'forkee': {'id': 28688604, 'name': 'awesome-c...
228      {'forkee': {'id': 28688618, 'name': 'Java-WebS...
241      {'forkee': {'id': 28688620, 'name': 'Developer...
265      {'forkee': {'id': 28688624, 'name': 'Octopress...
                               ...
11245    {'forkee': {'id': 28689731, 'name': 'App-Wallf...
11248    {'forkee': {'id': 28689732, 'name': 'joy.js', ...
11271    {'forkee': {'id': 28689737, 'name': 'BatteryPe...
11301    {'forkee': {'id': 28689738, 'name': 'jquery-js...
11304    {'forkee': {'id': 28689739, 'name': 'Flat-UI',...
Name: payload, Length: 355, dtype: object